                                                                                                                           
version: "3.1"
services:
  webserver:
      build:
        context: .webserver
        args:
          USERNAME: $USER
          USERID: $USERID
      ports:
        - "80:80"
      volumes:
        - "./:/var/www/html/"
        - "./.webserver/000-default.conf:/etc/apache2/sites-enabled/000-default.conf"
  volumes:
    mysqldata: null